services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aula22
      MYSQL_USER: aula22
      MYSQL_PASSWORD: aula22
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql